### ISSUE TITLE
Add to spago package-set

### ISSUE THREAD

**Issue by andys8** [dewey92/purescript-classnames#1]
This package looks nice. Maybe it can be added to the spago package-set:
https://github.com/purescript/package-sets#add-your-package

**Comment by dewey92** [comment]
Hi Andy! Thanks, glad you like this library!

I've been away from Purescript for a couple of months and I might be missing out something. I wasn't aware that `package-sets` exists. How does it actually differ from https://github.com/purescript/registry/pull/26?

**Comment by andys8** [comment]
I'm quite new to PureScript myself. From what I read my understanding is that `registry` is about existing and unique names, where as `package-sets` defines a set of packages with versions that should work together.

Here it says the precondition of being in the package-set is that the name is listed in the registry or bower.

https://github.com/purescript/package-sets/blob/master/CONTRIBUTING.md#general

And here is a script to verify it:

https://github.com/purescript/package-sets/blob/fe4cc5d5bda2f76786e7c6deccd80becfacf890c/verify-packages-in-registry.sh#L8

**Comment by dewey92** [comment]
Ah, so it's sort of like Haskell's hackage where libraries are curated to make sure they work together :)

Cool, I'll add this library to package-sets when I got the time to do it. Thanks, Andy!

**Comment by dewey92** [comment]
@andys8 Oops, I was going to add to package-sets just now but you did it already! Many thanks! 🙌🏻
